/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FlightDetails: typeof import('./src/components/ui/FlightDetails.vue')['default']
    PriceRange: typeof import('./src/components/ui/PriceRange.vue')['default']
    PumpFill: typeof import('./src/components/ui/PumpFill.vue')['default']
    TranslateLanguage: typeof import('./src/components/ui/TranslateLanguage.vue')['default']
  }
}
